from django.conf.urls import url

from .views import (UserLoginView,
                    loginForm,
                    logoutView,
                    person_create,
                    person_update,
                    person_delete,
                    UserCreateView,
                    persons_list_creator,
                    users_list,
                    disable_user,
                    enable_user,
                    search,
                    results,
                    person_list,
                    successful,
                    successful_user,
                    successful_edition,
                    successful_deletion,
)

urlpatterns = [
    url('^login/$', UserLoginView.as_view(), name='login'),
    url('^logout/$', logoutView, name='logout'),
    url('^tologin/$', loginForm, name='tologin'),
    url('^create/$', person_create, name='create'),
    url('^edit/(?P<pk>\d+)/$', person_update, name='update'),
    url('^delete/(?P<pk>\d+)/$', person_delete, name='delete'),
    url('^createuser/$', UserCreateView.as_view(), name='createuser'),
    url('^users/$', users_list, name='users'),
    url('^personsuser/(?P<pk_user>\d+)/$', persons_list_creator, name='personsuser'),
    url('^disable/(?P<pk>\d+)/$', disable_user, name='disable'),
    url('^enable/(?P<pk>\d+)/$', enable_user, name='enable'),
    url('^search/$', search, name='search'),
    url('^results/$', results, name='results'),
    url('^successful/$', successful, name='successful'),
    url('^successfuluser/$', successful_user, name='succesfuluser'),
    url('^successfuledition/$', successful_edition, name='successfuledition'),
    url('^successfuldeletion/$', successful_deletion, name='successfuldeletion'),
    url('^$', person_list, name='all'),
]
