# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_remove_person_usermodifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 30, 21, 34, 13, 166839, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
