# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_person_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.DateField(default=datetime.datetime(2016, 6, 2, 0, 17, 43, 530946, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default=datetime.datetime(2016, 6, 2, 0, 17, 50, 244644, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='userCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
